kind: pipeline
type: docker
name: java-springboot-mvn-builder

steps:
  - name: build
    image: maven
    commands:
      - pwd
      - ls -ltr
      - echo "$PG_DB_HOST" | rev
      - echo "$PG_DB_PORT" | rev
      - echo "$PG_DB_USER" | rev
      - echo "$PG_DB_PWD" | rev
    environment:
      PG_DB_HOST:
        from_secret: PG_DB_HOST
      PG_DB_PORT:
        from_secret: PG_DB_PORT
      PG_DB_USER:
        from_secret: PG_DB_USER
      PG_DB_PWD:
        from_secret: PG_DB_PWD