kind: pipeline
type: docker
name: java-springboot-mvn-builder

steps:
  - name: build
    image: maven
    commands:
      - mvn package
      - ls -ltr
      - ls -ltr ./target/
    environment:
      PG_DB_HOST:
        from_secret: PG_DB_HOST
      PG_DB_PORT:
        from_secret: PG_DB_PORT
      PG_DB_USER:
        from_secret: PG_DB_USER
      PG_DB_PWD:
        from_secret: PG_DB_PWD